const products = [
    {
        "id": "bb9614aa-d0a6-45ec-90f3-25b7fb77b9d9",
        "id_auto": 773,
        'name': "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "dcfddf38-e2c8-4709-a4d7-33bcf233ec9b",
        "id_auto": 774,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "0ff09a20-7077-4e1e-b0e8-383efea40276",
        "id_auto": 775,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "eb457108-ac37-4640-a56b-795f36c885d4",
        "id_auto": 776,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "858b0882-cae2-490b-9da7-268f78dd0f11",
        "id_auto": 777,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "6728ca3b-ab53-486b-8659-7e40ffb0dcd5",
        "id_auto": 778,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "07fd9f94-ed59-4a7c-9c45-7c0884e592f9",
        "id_auto": 779,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "7a4f646b-5cea-432c-bcf2-f23f58813802",
        "id_auto": 780,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "c7abe01c-ee16-45af-9fe9-df9e8495cdcf",
        "id_auto": 781,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "b57991a6-79d7-476d-b23f-dafa914da689",
        "id_auto": 782,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "56740688-a0eb-47bc-a5e5-39bcd3f8655e",
        "id_auto": 783,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "0fd7c5c2-6c3c-458b-ad23-14a28f0bf92b",
        "id_auto": 784,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "ef1f3b13-b051-43fe-8548-93b2328e9173",
        "id_auto": 785,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "f3619bb7-cf9d-4a5f-a402-f57f8d848e96",
        "id_auto": 786,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "b161b511-cf48-4c23-8946-0410023216c7",
        "id_auto": 787,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "cdd02a58-4757-45a8-bd6c-82e2ac0e15c2",
        "id_auto": 788,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "896d191f-5a8d-4927-b04e-88317e42ceca",
        "id_auto": 789,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "47ceb5f3-0e0d-4dfa-aa67-6f0c31a49758",
        "id_auto": 790,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "fe95bb30-2282-4d3b-a284-3f012fb4e737",
        "id_auto": 791,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "c34784bc-ec3f-4b65-a29c-d04e2be23400",
        "id_auto": 792,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "dab04c51-3cd6-48c3-9188-e3624b7d8b61",
        "id_auto": 793,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "cf4cb40c-6ccd-454d-ab48-355eb7f0eea3",
        "id_auto": 794,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "13b0a150-ee4a-40e7-9509-51ee4d3a1970",
        "id_auto": 795,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "7cdf8983-2255-4096-9948-8617cdf2139d",
        "id_auto": 796,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "16eef406-bb45-4906-a448-7cfbd6bd1300",
        "id_auto": 797,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "a6aee009-d337-4569-8c0c-d145afb4529f",
        "id_auto": 798,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "f768b2c7-5f37-4376-9cc0-d4d478c2a354",
        "id_auto": 799,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "fdd0c3fa-ee04-49a1-bce4-f5cb3649a387",
        "id_auto": 800,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "52e5d887-acbc-4b3f-a597-706f9dde255c",
        "id_auto": 801,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "548ca61f-7e04-469f-98c5-7650cd55aefd",
        "id_auto": 802,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "7f78c65c-dc7d-4a1f-88e9-9ce27860fbd5",
        "id_auto": 803,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "6fb923bc-6480-45e7-88c4-e289760bffd6",
        "id_auto": 804,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "11357860-1403-4d4e-90f2-5eaf9f36af5b",
        "id_auto": 805,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "c6b3facd-1620-4664-9364-947fd1ebb156",
        "id_auto": 806,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "f32bac78-70b6-4e02-814a-1027a89c8b62",
        "id_auto": 807,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "0f715e84-46d9-4d08-8b1f-7390558f3312",
        "id_auto": 808,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "c1813532-7216-4e93-95a6-273e6f034d1f",
        "id_auto": 809,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "55fe8522-6736-4885-aafd-389ee3daeb56",
        "id_auto": 810,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "18e6eef6-76f6-472f-84d4-b268d2d717bb",
        "id_auto": 811,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "87ee8f27-75d8-4181-a412-c23d2fdf7917",
        "id_auto": 812,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "e66061f9-183d-4260-b359-29b5be9e9631",
        "id_auto": 813,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "b8a2bfc8-3cba-4101-9754-19f8391df813",
        "id_auto": 814,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "c28da5c8-f850-44bd-b3a1-bf73ba5a1c84",
        "id_auto": 815,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "0dfeb13e-290c-4f5e-9945-59cc4e3a0869",
        "id_auto": 816,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "a82ca3ec-86aa-42e9-b1a7-049aa0e0e3b7",
        "id_auto": 817,
        "name": "morele alar cenowy",
        "siteName": "mo - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "img",
        "limitQuantity": "0",
        "img": "50",
        "category": "category"
    },
    {
        "id": "fca6fd49-1a33-4a5e-95d1-5df7e03cb757",
        "id_auto": 772,
        "name": "xkom product",
        "siteName": "UPDATE - name",
        "siteLink": "name",
        "oldPrice": "new",
        "newPrice": "old",
        "remainingQuantity": "9999",
        "limitQuantity": "9999",
        "img": "limit",
        "category": "category"
    }
]

export default products;